// This is a mock database of paint colours from UK vendors
// In a real application, this would be stored in a database and would be much more comprehensive

export const paintDatabase = {
  vendors: [
    {
      name: "Dulux",
      colours: [
        {
          name: "Timeless",
          code: "00YY 63/012",
          hex: "#E8E5DE",
          url: "https://www.dulux.co.uk/en/colour-details/timeless",
        },
        {
          name: "Polished Pebble",
          code: "10YY 54/034",
          hex: "#D5CFC3",
          url: "https://www.dulux.co.uk/en/colour-details/polished-pebble",
        },
        {
          name: "Egyptian Cotton",
          code: "30YY 67/084",
          hex: "#E4DBCA",
          url: "https://www.dulux.co.uk/en/colour-details/egyptian-cotton",
        },
        {
          name: "Goose Down",
          code: "10YY 46/041",
          hex: "#C1B9AB",
          url: "https://www.dulux.co.uk/en/colour-details/goose-down",
        },
        {
          name: "Soft Stone",
          code: "30YY 56/060",
          hex: "#D0C7B5",
          url: "https://www.dulux.co.uk/en/colour-details/soft-stone",
        },
        {
          name: "Nutmeg White",
          code: "70YR 67/088",
          hex: "#E5D8C8",
          url: "https://www.dulux.co.uk/en/colour-details/nutmeg-white",
        },
        {
          name: "Natural Hessian",
          code: "00YY 47/205",
          hex: "#C4B59A",
          url: "https://www.dulux.co.uk/en/colour-details/natural-hessian",
        },
        {
          name: "Chalk Blush",
          code: "10YR 64/035",
          hex: "#E1D5CB",
          url: "https://www.dulux.co.uk/en/colour-details/chalk-blush",
        },
        {
          name: "Perfectly Taupe",
          code: "70YR 38/072",
          hex: "#A99686",
          url: "https://www.dulux.co.uk/en/colour-details/perfectly-taupe",
        },
        {
          name: "Pebble Shore",
          code: "50YR 53/011",
          hex: "#C9C2B8",
          url: "https://www.dulux.co.uk/en/colour-details/pebble-shore",
        },
        {
          name: "Jasmine White",
          code: "45YY 83/043",
          hex: "#F5F0E1",
          url: "https://www.dulux.co.uk/en/colour-details/jasmine-white",
        },
        {
          name: "Almond White",
          code: "90YR 83/030",
          hex: "#F5EFE3",
          url: "https://www.dulux.co.uk/en/colour-details/almond-white",
        },
        // Additional colours
        {
          name: "Mineral Mist",
          code: "30BB 72/015",
          hex: "#E2E6E7",
          url: "https://www.dulux.co.uk/en/colour-details/mineral-mist",
        },
        {
          name: "Tranquil Dawn",
          code: "45GY 72/106",
          hex: "#D9E0D9",
          url: "https://www.dulux.co.uk/en/colour-details/tranquil-dawn",
        },
        {
          name: "Willow Tree",
          code: "90YY 35/169",
          hex: "#8D8B6C",
          url: "https://www.dulux.co.uk/en/colour-details/willow-tree",
        },
        {
          name: "Sapphire Springs",
          code: "30BG 40/094",
          hex: "#7A9A9D",
          url: "https://www.dulux.co.uk/en/colour-details/sapphire-springs",
        },
        {
          name: "Pressed Petal",
          code: "10YR 56/234",
          hex: "#D9B09A",
          url: "https://www.dulux.co.uk/en/colour-details/pressed-petal",
        },
        {
          name: "Blush Pink",
          code: "90RR 72/119",
          hex: "#F0D7D8",
          url: "https://www.dulux.co.uk/en/colour-details/blush-pink",
        },
        {
          name: "Dusted Fondant",
          code: "10RR 54/101",
          hex: "#D3B0B0",
          url: "https://www.dulux.co.uk/en/colour-details/dusted-fondant",
        },
        {
          name: "Soft Truffle",
          code: "00YY 26/220",
          hex: "#8A7A5F",
          url: "https://www.dulux.co.uk/en/colour-details/soft-truffle",
        },
      ],
    },
    {
      name: "Farrow & Ball",
      colours: [
        {
          name: "Skimming Stone",
          code: "241",
          hex: "#E5E1D7",
          url: "https://www.farrow-ball.com/paint-colours/skimming-stone",
        },
        {
          name: "Elephant's Breath",
          code: "229",
          hex: "#BFB9AD",
          url: "https://www.farrow-ball.com/paint-colours/elephants-breath",
        },
        {
          name: "Strong White",
          code: "2001",
          hex: "#ECE9E1",
          url: "https://www.farrow-ball.com/paint-colours/strong-white",
        },
        {
          name: "Cornforth White",
          code: "228",
          hex: "#C8C4BC",
          url: "https://www.farrow-ball.com/paint-colours/cornforth-white",
        },
        {
          name: "Slipper Satin",
          code: "2004",
          hex: "#E7E2D6",
          url: "https://www.farrow-ball.com/paint-colours/slipper-satin",
        },
        {
          name: "Joa's White",
          code: "226",
          hex: "#E1D9C6",
          url: "https://www.farrow-ball.com/paint-colours/joas-white",
        },
        { name: "Dimity", code: "2008", hex: "#ECE3D3", url: "https://www.farrow-ball.com/paint-colours/dimity" },
        {
          name: "Oxford Stone",
          code: "264",
          hex: "#C8BCA7",
          url: "https://www.farrow-ball.com/paint-colours/oxford-stone",
        },
        {
          name: "Hardwick White",
          code: "5",
          hex: "#C5BFB0",
          url: "https://www.farrow-ball.com/paint-colours/hardwick-white",
        },
        {
          name: "Shaded White",
          code: "201",
          hex: "#E0D9CC",
          url: "https://www.farrow-ball.com/paint-colours/shaded-white",
        },
        { name: "Bone", code: "15", hex: "#D8CFC0", url: "https://www.farrow-ball.com/paint-colours/bone" },
        {
          name: "School House White",
          code: "291",
          hex: "#E8E1D4",
          url: "https://www.farrow-ball.com/paint-colours/school-house-white",
        },
        // Additional colours
        {
          name: "Hague Blue",
          code: "30",
          hex: "#2D3A4B",
          url: "https://www.farrow-ball.com/paint-colours/hague-blue",
        },
        {
          name: "Stiffkey Blue",
          code: "281",
          hex: "#4A5366",
          url: "https://www.farrow-ball.com/paint-colours/stiffkey-blue",
        },
        {
          name: "Railings",
          code: "31",
          hex: "#36393C",
          url: "https://www.farrow-ball.com/paint-colours/railings",
        },
        {
          name: "Green Smoke",
          code: "47",
          hex: "#636F68",
          url: "https://www.farrow-ball.com/paint-colours/green-smoke",
        },
        {
          name: "Setting Plaster",
          code: "231",
          hex: "#E4C8B7",
          url: "https://www.farrow-ball.com/paint-colours/setting-plaster",
        },
        {
          name: "Dead Salmon",
          code: "28",
          hex: "#D0B4A0",
          url: "https://www.farrow-ball.com/paint-colours/dead-salmon",
        },
        {
          name: "Sulking Room Pink",
          code: "295",
          hex: "#A78A8A",
          url: "https://www.farrow-ball.com/paint-colours/sulking-room-pink",
        },
        {
          name: "Calke Green",
          code: "34",
          hex: "#6A7062",
          url: "https://www.farrow-ball.com/paint-colours/calke-green",
        },
      ],
    },
    {
      name: "Crown",
      colours: [
        { name: "Soft Linen", code: "CR100", hex: "#E9E5DC", url: "https://www.crownpaints.co.uk/products/soft-linen" },
        {
          name: "Ivory Cream",
          code: "CR120",
          hex: "#F0E8D8",
          url: "https://www.crownpaints.co.uk/products/ivory-cream",
        },
        { name: "Wheatgrass", code: "CR190", hex: "#D9D0BE", url: "https://www.crownpaints.co.uk/products/wheatgrass" },
        {
          name: "Chalk White",
          code: "CR110",
          hex: "#F1EDE5",
          url: "https://www.crownpaints.co.uk/products/chalk-white",
        },
        { name: "Hare", code: "CR210", hex: "#C7BFB0", url: "https://www.crownpaints.co.uk/products/hare" },
        { name: "Aged White", code: "CR130", hex: "#E8E0D1", url: "https://www.crownpaints.co.uk/products/aged-white" },
        {
          name: "Toasted Almond",
          code: "CR220",
          hex: "#D5C8B6",
          url: "https://www.crownpaints.co.uk/products/toasted-almond",
        },
        {
          name: "Cream White",
          code: "CR140",
          hex: "#F0E9DB",
          url: "https://www.crownpaints.co.uk/products/cream-white",
        },
        {
          name: "Pebble Grey",
          code: "CR230",
          hex: "#C5BEB2",
          url: "https://www.crownpaints.co.uk/products/pebble-grey",
        },
        {
          name: "Antique Cream",
          code: "CR150",
          hex: "#EAE0CD",
          url: "https://www.crownpaints.co.uk/products/antique-cream",
        },
        { name: "Taupe", code: "CR240", hex: "#C1B5A5", url: "https://www.crownpaints.co.uk/products/taupe" },
        { name: "Soft Khaki", code: "CR250", hex: "#BFB5A1", url: "https://www.crownpaints.co.uk/products/soft-khaki" },
        // Additional colours
        {
          name: "Oxford Blue",
          code: "CR420",
          hex: "#2E4055",
          url: "https://www.crownpaints.co.uk/products/oxford-blue",
        },
        {
          name: "Teal",
          code: "CR430",
          hex: "#3A6A6D",
          url: "https://www.crownpaints.co.uk/products/teal",
        },
        {
          name: "Olive Green",
          code: "CR440",
          hex: "#6B7353",
          url: "https://www.crownpaints.co.uk/products/olive-green",
        },
        {
          name: "Sage Leaf",
          code: "CR450",
          hex: "#A9B09A",
          url: "https://www.crownpaints.co.uk/products/sage-leaf",
        },
        {
          name: "Millionaire",
          code: "CR460",
          hex: "#8E6E5B",
          url: "https://www.crownpaints.co.uk/products/millionaire",
        },
        {
          name: "Pale Terracotta",
          code: "CR470",
          hex: "#D8B09E",
          url: "https://www.crownpaints.co.uk/products/pale-terracotta",
        },
        {
          name: "Dusty Pink",
          code: "CR480",
          hex: "#D8B8B8",
          url: "https://www.crownpaints.co.uk/products/dusty-pink",
        },
        {
          name: "Charcoal Grey",
          code: "CR490",
          hex: "#4A4A4A",
          url: "https://www.crownpaints.co.uk/products/charcoal-grey",
        },
      ],
    },
    {
      name: "Little Greene",
      colours: [
        {
          name: "French Grey",
          code: "161",
          hex: "#C5C5B7",
          url: "https://www.littlegreene.com/french-grey",
        },
        {
          name: "Portland Stone",
          code: "77",
          hex: "#D6CEBF",
          url: "https://www.littlegreene.com/portland-stone",
        },
        {
          name: "Slaked Lime",
          code: "105",
          hex: "#E9E2D0",
          url: "https://www.littlegreene.com/slaked-lime",
        },
        {
          name: "Rolling Fog",
          code: "143",
          hex: "#E0DCD1",
          url: "https://www.littlegreene.com/rolling-fog",
        },
        {
          name: "Linen Wash",
          code: "33",
          hex: "#E8E1D1",
          url: "https://www.littlegreene.com/linen-wash",
        },
        {
          name: "Bone China Blue",
          code: "107",
          hex: "#DCE3E1",
          url: "https://www.littlegreene.com/bone-china-blue",
        },
        {
          name: "Inox",
          code: "224",
          hex: "#D0D1CD",
          url: "https://www.littlegreene.com/inox",
        },
        {
          name: "Fescue",
          code: "231",
          hex: "#BEC3B5",
          url: "https://www.littlegreene.com/fescue",
        },
        {
          name: "Sage Green",
          code: "80",
          hex: "#B9BEA7",
          url: "https://www.littlegreene.com/sage-green",
        },
        {
          name: "Pale Lupin",
          code: "278",
          hex: "#E2D9D9",
          url: "https://www.littlegreene.com/pale-lupin",
        },
        {
          name: "Dorchester Pink",
          code: "213",
          hex: "#E9D9D2",
          url: "https://www.littlegreene.com/dorchester-pink",
        },
        {
          name: "Mirage",
          code: "21",
          hex: "#D8C9B6",
          url: "https://www.littlegreene.com/mirage",
        },
      ],
    },
  ],
}
